# Generated by Django 5.1.6 on 2025-04-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('cta_button', models.CharField(max_length=100)),
                ('feature_title', models.CharField(max_length=200)),
                ('feature_description', models.CharField(max_length=500)),
                ('feature_button', models.CharField(max_length=100)),
                ('footer_tagline', models.CharField(max_length=500)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('features', models.CharField(max_length=500)),
            ],
        ),
    ]
