# Generated by Django 5.2 on 2025-04-16 16:03

from django.db import migrations

def create_default_pricing_plans(apps, schema_editor):
    PricingPlan = apps.get_model('landing_page', 'PricingPlan')
    # Create default pricing plans
    PricingPlan.objects.create(
        title="Starter",
        price="$19/month",
        features="Basic Access, 5 Projects, Community Support"
    )

    PricingPlan.objects.create(
        title="Professional",
        price="$49/month",
        features="All Starter Features, Unlimited Projects, Priority Support"
    )

    PricingPlan.objects.create(
        title="Enterprise",
        price="$99/month",
        features="Everything in Pro, Dedicated Manager, Custom Integrations"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_auto_20250416_2256'),
    ]

    operations = [
        migrations.RunPython(create_default_pricing_plans),
    ]
