# Generated by Django 5.2 on 2025-04-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('features', models.TextField(help_text='Comma-separated list')),
            ],
        ),
        migrations.RenameField(
            model_name='homepagecontent',
            old_name='cta_text',
            new_name='cta_button',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='enterprise_features',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='enterprise_price',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='enterprise_title',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='pro_features',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='pro_price',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='pro_title',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='starter_features',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='starter_price',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='starter_title',
        ),
    ]
