# Generated by Django 5.2 on 2025-04-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_homepagecontent_feature_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='subtitle',
            field=models.CharField(max_length=200),
        ),
    ]
