# Generated by Django 5.2 on 2025-04-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_homepagecontent_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='contact_email',
            field=models.EmailField(default='marketing@terra.systems', max_length=254),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='cta_button',
            field=models.CharField(default='Explore More', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='feature_button',
            field=models.CharField(default='Explore More', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='feature_description',
            field=models.CharField(default='Terra Systems drives business growth through Digital Transformation (automating operations for SMEs), Audio-Visual Innovations (crafting cutting-edge experiences), and BPO Solutions (optimizing workflows). We deliver Cybersecurity protection against evolving threats, Branding/Marketing strategies to position brands decisively, and Public Relations to amplify reach—equipping businesses to thrive securely and impactfully in dynamic markets.', max_length=500),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='feature_title',
            field=models.CharField(default='Next-Gen Experiences', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='footer_tagline',
            field=models.CharField(default='Crafting the future, one pixel at a time.', max_length=500),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='subtitle',
            field=models.CharField(default='Experience the next generation of technology.', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='title',
            field=models.CharField(default='TERRA SYSTEMS', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='contact_phone',
            field=models.CharField(default='(65) 6876 580', max_length=20),
        ),
    ]
