# Generated by Django 5.2 on 2025-04-16 15:57

from django.db import migrations

def populate_homepage_content(apps, schema_editor):
    HomePageContent = apps.get_model('accounts', 'HomePageContent')
    # Check if the content exists, if not create it with defaults
    if not HomePageContent.objects.exists():
        HomePageContent.objects.create(
            title="TERRA SYSTEMS",
            subtitle="Your gateway to digital transformation",
            cta_button="Get Started",
            feature_title="Next-Gen Experiences",
            feature_description="Terra Systems drives business growth through Digital Transformation (automating operations for SMEs), Audio-Visual Innovations (crafting cutting-edge experiences), and BPO Solutions (optimizing workflows). We deliver Cybersecurity protection against evolving threats, Branding/Marketing strategies to position brands decisively, and Public Relations to amplify reach—equipping businesses to thrive securely and impactfully in dynamic markets.",
            feature_button="Explore More",
            footer_tagline="Crafting the future, one pixel at a time.",
            contact_email="marketing@terra.systems",
            contact_phone="(65) 6876 5800"
        )

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_homepagecontent_contact_email_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_homepage_content),
    ]
