# Generated by Django 5.2 on 2025-04-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20250416_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='contact_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='cta_button',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='feature_button',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='feature_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='feature_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='footer_tagline',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='subtitle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
