# Generated by Django 5.1.6 on 2025-04-16 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_homepagecontent_contact_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageContent',
        ),
        migrations.DeleteModel(
            name='PricingPlan',
        ),
    ]
